/**
 * Pre-registered task definitions for the delegation-signal corpus.
 *
 * Feature labels are assigned from how each task is constructed -- editable scope size,
 * what the validator does, how completely the prompt pins the required behaviour, and what
 * would break if a wrong change were accepted. They are committed before any agent runs, so
 * no label can be adjusted after seeing an outcome.
 *
 * verificationCostClass is structural, not a stopwatch reading:
 *   cheap     - in-process assertions only, no child processes
 *   moderate  - spawns short child processes to resolve the package
 *   expensive - stages several repository copies and runs a full test suite in each
 */

const fullyReversible = "fully_reversible";

export const repositories = [
  {
    id: "version-core",
    fixturePath: "fixtures/version-core",
    upstream: {
      url: "https://github.com/npm/node-semver",
      revision: "6e05b7637396ac66522cff8731f07cfe0ef49a29",
      ref: "v7.8.5",
      licenseSpdx: "ISC",
    },
    baselineChecks: [
      ["node", "--check", "index.js"],
      ["node", "-e", "require('./index.js')"],
    ],
  },
  {
    id: "glob-matcher-core",
    fixturePath: "fixtures/glob-matcher-core",
    upstream: {
      url: "https://github.com/micromatch/picomatch",
      revision: "4f41a8edade7a5ab19832f7b40ecce46b288767f",
      ref: "4.0.5",
      licenseSpdx: "MIT",
    },
    baselineChecks: [
      ["node", "--check", "index.js"],
      ["node", "-e", "require('./index.js')"],
    ],
  },
  {
    id: "cli-command-core",
    fixturePath: "fixtures/cli-command-core",
    upstream: {
      url: "https://github.com/tj/commander.js",
      revision: "ba6d13ddb4243e5913367734f8c159089ffe7834",
      ref: "v15.0.0",
      licenseSpdx: "MIT",
    },
    baselineChecks: [
      ["node", "--check", "index.js"],
      ["node", "--input-type=module", "-e", "await import('./index.js')"],
    ],
  },
];

export const tasks = [
  // ---------------------------------------------------------------- version-core
  {
    id: "version-diff-release-type",
    repositoryId: "version-core",
    class: "bug_fix",
    title: "Restore prerelease-aware release-type diffing",
    editableScope: ["functions/diff.js"],
    validator: "validators/version-diff.mjs",
    knownGood: "known-good/version-diff.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "`diff(a, b)` reports which release type separates two versions. Transitions out of a",
      "prerelease are currently reported incorrectly: for example `diff('1.0.0-1', '1.0.0')` returns",
      "'prerelease' when it must return 'major', and `diff('1.1.0-1', '1.1.0')` must return 'minor'.",
      "",
      "Fix `functions/diff.js` so that:",
      "- identical versions, and versions differing only in build metadata, return null;",
      "- ordinary release steps return 'major' / 'minor' / 'patch';",
      "- a step *into* a prerelease keeps the 'pre' prefix ('premajor' / 'preminor' / 'prepatch');",
      "- two prereleases of the same main version return 'prerelease';",
      "- a step *out of* a prerelease is classified by how much of the main version is actually",
      "  being left behind: leaving a prerelease whose minor and patch are both zero is always a",
      "  'major' step, and when the main version is otherwise unchanged the answer is 'minor' if the",
      "  minor is non-zero and the patch is zero, otherwise 'patch';",
      "- the result does not depend on argument order;",
      "- invalid version strings still raise a TypeError.",
      "",
      "Read `classes/semver.js` for `compare` and `compareMain` before changing anything.",
    ],
    metadata: {
      representativeReason:
        "Release-type classification across prerelease boundaries is real upstream logic that requires reasoning about two comparison helpers rather than editing one expression.",
      validatorEstablishes:
        "A 22-pair release-type table asserted in both argument orders, plus TypeError on invalid input.",
      limitations: "Does not cover loose parsing or the includePrerelease option.",
    },
  },
  {
    id: "version-coerce-options",
    repositoryId: "version-core",
    class: "small_feature",
    title: "Add rtl and includePrerelease coercion options",
    editableScope: ["functions/coerce.js"],
    validator: "validators/version-coerce.mjs",
    knownGood: "known-good/version-coerce.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "unit_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "`coerce(version, options)` currently supports only plain left-to-right coercion of the",
      "major/minor/patch triple. The documented `rtl` and `includePrerelease` options are missing.",
      "",
      "Extend `functions/coerce.js` so that:",
      "- `{ rtl: true }` coerces the right-most coercible triple that does not share a terminus with a",
      "  more left-ward one, so '1.2.3.4' coerces to '2.3.4' and '1.2.3.4.5' to '3.4.5';",
      "- `{ includePrerelease: true }` carries prerelease identifiers and build metadata through, so",
      "  '1.2.3-alpha.1+build.2' coerces to a version with prerelease alpha.1 and build ['build','2'];",
      "- the two options compose: coerce('1.2.3.4-rc', { rtl: true, includePrerelease: true }) is",
      "  '2.3.4-rc';",
      "- existing no-option behaviour is unchanged, including instance passthrough, numeric input, and",
      "  null for uncoercible or non-string input;",
      "- repeated calls return the same answer (a global regular expression must not leak lastIndex).",
      "",
      "`internal/re.js` already defines the tokens you need; find them before writing code.",
    ],
    metadata: {
      representativeReason:
        "Adding documented option handling to an existing public function is ordinary library feature work, and the right-to-left variant cannot be written without reading the shared regular-expression table in another file.",
      validatorEstablishes:
        "Preserved no-option coercion, right-to-left coercion, prerelease and build capture, both options combined, and call-to-call stability.",
      limitations: "Does not cover the loose option or coercion of ranges.",
    },
  },
  {
    id: "version-lru-cache-eviction",
    repositoryId: "version-core",
    class: "refactor",
    title: "Make the internal parse cache a bounded LRU",
    editableScope: ["internal/lrucache.js"],
    validator: "validators/version-lru-cache.mjs",
    knownGood: "known-good/version-lru-cache.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "`internal/lrucache.js` is currently an unbounded Map wrapper: it declares a `max` of 1000 but",
      "never evicts, and reads do not affect retention. It backs range and version parsing (see",
      "`classes/range.js` and `internal/parse-options.js`), so on a long-lived process it grows without",
      "bound.",
      "",
      "Refactor it into a real bounded LRU cache, preserving its current interface:",
      "- `max` stays 1000 by default;",
      "- `get(key)` returns the value or undefined, and marks the key as most recently used;",
      "- `set(key, value)` returns the cache itself, and never stores an entry when value is undefined;",
      "- `delete(key)` returns whether the key was present;",
      "- once `max` entries are held, inserting a new key evicts the least recently used key, so the",
      "  cache never retains more than `max` entries no matter how much churn it sees.",
      "",
      "Library behaviour must not change: parsing many more distinct ranges than the cache can hold",
      "must still produce identical answers.",
    ],
    metadata: {
      representativeReason:
        "Replacing a degenerate data structure with a correct one while holding an existing interface fixed is a common maintenance refactor.",
      validatorEstablishes:
        "Interface preservation, eviction at capacity, recency promotion on read, a hard retention bound under 3x churn, and unchanged answers across 1500 distinct ranges.",
      limitations:
        "Does not assert re-setting an existing key, where upstream behaviour is idiosyncratic.",
    },
  },
  {
    id: "version-range-test-repair",
    repositoryId: "version-core",
    class: "test_repair",
    title: "Repair the stale range test suite",
    editableScope: ["test/range.test.js"],
    validator: "validators/version-range-tests.mjs",
    knownGood: "known-good/version-range-tests.json",
    validatorTimeoutMs: 180_000,
    features: {
      acceptanceCriteriaType: "integration_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "moderate",
      verificationCostClass: "expensive",
      reversibility: fullyReversible,
    },
    prompt: [
      "`test/range.test.js` is a node:test suite covering range behaviour. It was written against older",
      "expectations and now fails: run `node --test test/range.test.js` to see it.",
      "",
      "Repair the suite so that it passes against the library as it actually behaves, and so that it",
      "still genuinely characterises that behaviour. Correct the wrong expectations rather than deleting",
      "or weakening the assertions: the suite must continue to cover, at minimum, versions that do",
      "satisfy a range, versions that do not satisfy a range, prerelease handling, pairs of ranges that",
      "do intersect, pairs that do not, and range parsing and validation.",
      "",
      "Only `test/range.test.js` may be changed. The library itself is correct.",
    ],
    metadata: {
      representativeReason:
        "Repairing a stale suite without letting it rot into a suite that asserts nothing is routine maintenance, and it is only decidable with an external check.",
      validatorEstablishes:
        "The suite passes against the unmodified library and still fails against four appended behavioural mutants, so assertions cannot be deleted or trivialised.",
      limitations:
        "Mutation coverage is limited to four Range mutants and does not measure line coverage.",
    },
  },
  {
    id: "version-subpath-exports",
    repositoryId: "version-core",
    class: "config_change",
    title: "Publish documented subpaths and keep internals private",
    editableScope: ["package.json"],
    validator: "validators/version-exports.mjs",
    knownGood: "known-good/version-exports.json",
    validatorTimeoutMs: 120_000,
    features: {
      acceptanceCriteriaType: "static_analysis",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "moderate",
      reversibility: "reversible_with_review",
    },
    prompt: [
      "This package has no `exports` map, so every internal file is reachable by consumers and nothing",
      "is a declared entry point. Add packaging configuration to `package.json` so that:",
      "- the package root resolves to `./index.js`;",
      "- `<pkg>/classes/<name>`, `<pkg>/functions/<name>` and `<pkg>/ranges/<name>` resolve to the",
      "  matching `.js` file in that directory (for example `<pkg>/functions/parse`);",
      "- `<pkg>/package.json` remains resolvable;",
      "- everything under `internal/` is NOT reachable from outside the package;",
      "- deep paths that name a file directly, such as `<pkg>/index.js`, are NOT reachable;",
      "- a `files` array is declared that includes `classes/`, `functions/`, `internal/`, `ranges/` and",
      "  `index.js`.",
      "",
      "Do not change the package name, license or main field, and do not add a `type` field.",
    ],
    metadata: {
      representativeReason:
        "Declaring public entry points while hiding internals is routine packaging work whose failure mode -- accidentally publishing internals -- is invisible without resolving the package for real.",
      validatorEstablishes:
        "The candidate is staged under node_modules and Node's own resolver decides which subpaths load, so a plausible-looking but non-working exports block is rejected.",
      limitations: "Does not cover conditional exports, types entries, or dual CJS/ESM packaging.",
    },
  },

  // ---------------------------------------------------------- glob-matcher-core
  {
    id: "glob-scan-negation",
    repositoryId: "glob-matcher-core",
    class: "bug_fix",
    title: "Stop treating a negated extglob as a negated pattern",
    editableScope: ["lib/scan.js"],
    validator: "validators/glob-scan.mjs",
    knownGood: "known-good/glob-scan.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "`scan(pattern)` splits a glob into a static base and a glob remainder, and reports flags",
      "describing what it found. It currently mis-scans negated extglobs.",
      "",
      "A leading `!` negates a pattern, so `scan('!a/b/*.js')` reports prefix '!', start 1, base 'a/b',",
      "glob '*.js' and negated true. But `!(` opens a *negated extglob*, which is part of the pattern",
      "and must not be consumed as a negation prefix: `scan('!(a|b)')` must report prefix '', start 0,",
      "base '', glob '!(a|b)', isExtglob true, negatedExtglob true and negated false. Today it reports",
      "the extglob as a negation instead.",
      "",
      "Fix `lib/scan.js` so both forms are classified correctly, without disturbing the base/glob split",
      "for ordinary patterns, `./` prefixes, braces, brackets, globstars or escaped `!` characters. The",
      "`nonegate` option must still suppress negation while leaving extglob detection intact.",
    ],
    metadata: {
      representativeReason:
        "A precedence bug between two lexer branches is a realistic parser defect that cannot be fixed without understanding the order in which the scanner consumes characters.",
      validatorEstablishes:
        "Every field of the scan result across 18 patterns covering negation, negated extglobs, other extglobs, globstars, braces, brackets, prefixes and escapes.",
      limitations: "Does not cover windows path scanning or the tokens/parts scan options.",
    },
  },
  {
    id: "glob-ignore-callbacks",
    repositoryId: "glob-matcher-core",
    class: "small_feature",
    title: "Add ignore patterns and match lifecycle callbacks",
    editableScope: ["lib/glob-match.js"],
    validator: "validators/glob-ignore.mjs",
    knownGood: "known-good/glob-ignore.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "unit_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "The matcher returned by the main export supports neither ignore patterns nor lifecycle",
      "callbacks. Add them in `lib/glob-match.js`:",
      "- `{ ignore }` takes a glob or array of globs; an input that matches the pattern but also matches",
      "  an ignore pattern must not match;",
      "- `{ onResult }` is called once with a result object for every input, whatever the outcome;",
      "- `{ onMatch }` is called only for inputs that end up matching;",
      "- `{ onIgnore }` is called only for inputs excluded by an ignore pattern;",
      "- the result object carries at least glob, regex, input, output and isMatch, with isMatch",
      "  reflecting the final decision;",
      "- an input that never matched the pattern is reported as a non-match, never as ignored;",
      "- the ignore pattern is evaluated without inheriting the caller's own callbacks.",
      "",
      "Existing matching behaviour, including array patterns and the returnObject form, must not change.",
    ],
    metadata: {
      representativeReason:
        "Adding option-driven behaviour to a closure that already exists is common library feature work, and the ordering between match, ignore and callback is easy to get subtly wrong.",
      validatorEstablishes:
        "Ignore semantics for single and array patterns, exact callback firing order and membership, result-object shape, and that ignore evaluation does not re-enter the caller's callbacks.",
      limitations: "Does not cover the format option or ignore interaction with windows paths.",
    },
  },
  {
    id: "glob-utils-helpers",
    repositoryId: "glob-matcher-core",
    class: "refactor",
    title: "Restore the path helper contract",
    editableScope: ["lib/utils.js"],
    validator: "validators/glob-utils.mjs",
    knownGood: "known-good/glob-utils.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "The helpers in `lib/utils.js` have been reduced to naive implementations that no longer honour",
      "their contract. Reimplement them, keeping every current export and signature:",
      "- `basename(path, { windows })` returns the last non-empty segment, treats a backslash as a",
      "  separator only when `windows` is set, and returns the last real segment when the path ends in",
      "  a separator;",
      "- `escapeLast(input, char, lastIdx)` escapes the last occurrence of `char` at or before `lastIdx`,",
      "  but skips an occurrence that is already escaped and continues searching leftwards;",
      "- `removePrefix(input, state)` strips a single leading './' and records it as `state.prefix`,",
      "  leaves `state` untouched when there was no prefix, and still works when `state` is omitted.",
      "",
      "The other helpers already behave correctly and must keep doing so. The wider library must be",
      "unaffected, including `matchBase`, which routes through `basename`.",
    ],
    metadata: {
      representativeReason:
        "Restoring a set of related helpers behind an unchanged interface, where several behaviours are wrong together, is a wholesale implementation replacement rather than a localized fix.",
      validatorEstablishes:
        "Separator and trailing-separator handling, already-escaped skipping, prefix recording including the optional state argument, preservation of the untouched helpers, and unchanged public matching.",
      limitations:
        "Does not cover the windows auto-detection path, which depends on the host platform.",
    },
  },
  {
    id: "glob-match-test-repair",
    repositoryId: "glob-matcher-core",
    class: "test_repair",
    title: "Repair the stale matcher test suite",
    editableScope: ["test/match.test.js"],
    validator: "validators/glob-match-tests.mjs",
    knownGood: "known-good/glob-match-tests.json",
    validatorTimeoutMs: 180_000,
    features: {
      acceptanceCriteriaType: "integration_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "moderate",
      verificationCostClass: "expensive",
      reversibility: fullyReversible,
    },
    prompt: [
      "`test/match.test.js` is a node:test suite covering glob matching. It was written against older",
      "expectations and now fails: run `node --test test/match.test.js` to see it.",
      "",
      "Repair the suite so that it passes against the library as it actually behaves, and so that it",
      "still genuinely characterises that behaviour. Correct the wrong expectations rather than deleting",
      "or weakening the assertions: the suite must continue to cover, at minimum, paths that do match a",
      "pattern, paths that do not, globstars, extglobs and negated extglobs, leading-bang negation,",
      "braces and bracket ranges, basename matching, and how `scan` splits a pattern into base and glob.",
      "",
      "Only `test/match.test.js` may be changed. The library itself is correct.",
    ],
    metadata: {
      representativeReason:
        "Repairing a stale suite without letting it rot into a suite that asserts nothing is routine maintenance, and it is only decidable with an external check.",
      validatorEstablishes:
        "The suite passes against the unmodified library and still fails against four appended behavioural mutants covering matching, scanning and basename matching.",
      limitations:
        "Mutation coverage is limited to four mutants and does not measure line coverage.",
    },
  },
  {
    id: "glob-subpath-exports",
    repositoryId: "glob-matcher-core",
    class: "config_change",
    title: "Publish named entry points and keep lib private",
    editableScope: ["package.json"],
    validator: "validators/glob-exports.mjs",
    knownGood: "known-good/glob-exports.json",
    validatorTimeoutMs: 120_000,
    features: {
      acceptanceCriteriaType: "static_analysis",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "moderate",
      reversibility: "reversible_with_review",
    },
    prompt: [
      "This package has no `exports` map, so every file under `lib/` is reachable by consumers. Add",
      "packaging configuration to `package.json` so that:",
      "- the package root resolves to `./index.js`;",
      "- `<pkg>/scan` resolves to `./lib/scan.js`;",
      "- `<pkg>/utils` resolves to `./lib/utils.js`;",
      "- `<pkg>/package.json` remains resolvable;",
      "- no path under `lib/` is reachable directly, and neither is `<pkg>/index.js`;",
      "- a `files` array is declared that includes `index.js` and `lib/`.",
      "",
      "Do not change the package name, license or main field, and do not add a `type` field.",
    ],
    metadata: {
      representativeReason:
        "Exposing a small set of named subpaths while hiding the implementation directory is routine packaging work with an invisible failure mode.",
      validatorEstablishes:
        "The candidate is staged under node_modules and Node's own resolver decides which subpaths load.",
      limitations: "Does not cover conditional exports or dual CJS/ESM packaging.",
    },
  },

  // ----------------------------------------------------------- cli-command-core
  {
    id: "cli-negated-option-name",
    repositoryId: "cli-command-core",
    class: "bug_fix",
    title: "Store negated options under their positive name",
    editableScope: ["lib/option.js"],
    validator: "validators/cli-negated-option.mjs",
    knownGood: "known-good/cli-negated-option.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "A `--no-x` flag is a negated option: it turns off `x`, so its parsed value must be stored under",
      "the positive attribute name. Today `--no-color` is stored as `noColor` instead of `color`.",
      "",
      "Fix `lib/option.js` so that a negated option's attribute name drops the `no-` prefix before",
      "camelcasing, so `--no-color` becomes `color` and `--no-check-updates` becomes `checkUpdates`,",
      "while positive options are unaffected and a long flag that merely begins with the letters 'no'",
      "-- such as `--nozzle` -- is not treated as negated.",
      "",
      "Parsing must then behave correctly: with only `--no-color` declared, the default is",
      "`{ color: true }` and passing the flag yields `{ color: false }`; when `--color` and `--no-color`",
      "are both declared they share the single `color` attribute and neither implies a default.",
    ],
    metadata: {
      representativeReason:
        "Attribute naming for negated flags is real option-parser logic whose failure silently produces the wrong key in parsed output.",
      validatorEstablishes:
        "Attribute naming for negated, positive and lookalike flags, plus end-to-end parsing for a lone negated flag and a positive/negative pair.",
      limitations: "Does not cover environment-variable or implied-option interactions.",
    },
  },
  {
    id: "cli-suggest-similar",
    repositoryId: "cli-command-core",
    class: "small_feature",
    title: "Suggest close matches for unknown commands and flags",
    editableScope: ["lib/suggestSimilar.js"],
    validator: "validators/cli-suggest-similar.mjs",
    knownGood: "known-good/cli-suggest-similar.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "unit_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "moderate",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "`suggestSimilar(word, candidates)` currently only recognises an exact match, so a mistyped",
      "command or flag produces no 'did you mean' hint. Implement real similarity matching in",
      "`lib/suggestSimilar.js`.",
      "",
      "Requirements:",
      "- compare `word` against `candidates` using an edit distance that also counts a transposition of",
      "  two adjacent characters as a single edit;",
      "- only consider candidates within 3 edits, and reject any whose similarity, measured as",
      "  (length - distance) / length against the longer of the two strings, is not greater than 0.4;",
      "- candidates of one character or shorter are never suggested;",
      "- keep only the closest candidates: a strictly better distance discards previous matches, an",
      "  equal distance joins them;",
      "- de-duplicate candidates, and sort the surviving suggestions with localeCompare;",
      "- when `word` starts with '--', compare without the leading dashes but restore them in the output;",
      "- return '' when nothing qualifies, '\\n(Did you mean X?)' for one match, and",
      "  '\\n(Did you mean one of A, B?)' for several;",
      "- return '' when candidates is empty, null or undefined.",
    ],
    metadata: {
      representativeReason:
        "Implementing a scored suggestion helper from a written specification is self-contained feature work with many boundary conditions.",
      validatorEstablishes:
        "Exact output strings across no-match, single-match, tie, duplicate, long-flag and closer-match cases, plus the unknown-command path that consumes it.",
      limitations:
        "Pins one similarity policy; other reasonable scoring schemes would be rejected. The prompt states the thresholds but not the algorithm, so the implementation choice is open.",
    },
  },
  {
    id: "cli-argument-contract",
    repositoryId: "cli-command-core",
    class: "refactor",
    title: "Restore the Argument class contract",
    editableScope: ["lib/argument.js"],
    validator: "validators/cli-argument.mjs",
    knownGood: "known-good/cli-argument.json",
    validatorTimeoutMs: 60_000,
    features: {
      acceptanceCriteriaType: "behavioral_contract",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "cheap",
      reversibility: fullyReversible,
    },
    prompt: [
      "The `Argument` class in `lib/argument.js` has been reduced to a stub: it no longer interprets its",
      "name syntax, its setters are not chainable, and choices are neither validated nor collected.",
      "Reimplement it, keeping every current export and method name:",
      "- `<name>` is a required argument, `[name]` is optional, a bare name is required, and a trailing",
      "  `...` inside the brackets makes it variadic; `name()` returns the bare name without any of that",
      "  punctuation;",
      "- `default()`, `argParser()`, `choices()`, `argRequired()` and `argOptional()` all return the",
      "  argument so they can be chained;",
      "- `choices(values)` copies the caller's array, and installs parsing that raises",
      "  `InvalidArgumentError` with the message `Allowed choices are a, b.` for a value outside the",
      "  list, and that accumulates values when the argument is variadic;",
      "- `_collectValue(value, previous)` starts a new array when there is nothing to extend and appends",
      "  otherwise;",
      "- `humanReadableArgName` renders the argument back to `<name>`, `[name]`, `<name...>` or",
      "  `[name...]`.",
      "",
      "A command declaring `<first>` and `[rest...]` must pass the first value and an array of the rest",
      "to its action handler.",
    ],
    metadata: {
      representativeReason:
        "Rebuilding a small class whose whole contract is degenerate, behind an interface other modules already depend on, is a wholesale implementation replacement.",
      validatorEstablishes:
        "Name-syntax parsing, chainability of every setter, choice validation and array copying, variadic collection, help rendering, and end-to-end argument dispatch through a command.",
      limitations: "Does not cover default-value descriptions in rendered help output.",
    },
  },
  {
    id: "cli-option-test-repair",
    repositoryId: "cli-command-core",
    class: "test_repair",
    title: "Repair the stale option test suite",
    editableScope: ["test/option.test.js"],
    validator: "validators/cli-option-tests.mjs",
    knownGood: "known-good/cli-option-tests.json",
    validatorTimeoutMs: 180_000,
    features: {
      acceptanceCriteriaType: "integration_test",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "moderate",
      verificationCostClass: "expensive",
      reversibility: fullyReversible,
    },
    prompt: [
      "`test/option.test.js` is a node:test suite covering option parsing. It was written against older",
      "expectations and now fails: run `node --test test/option.test.js` to see it.",
      "",
      "Repair the suite so that it passes against the library as it actually behaves, and so that it",
      "still genuinely characterises that behaviour. Correct the wrong expectations rather than deleting",
      "or weakening the assertions: the suite must continue to cover, at minimum, boolean options,",
      "options carrying a value, default values, how a long flag becomes a camelcased attribute name,",
      "whether an option is boolean, which flags an option recognises, how flags split into short and",
      "long forms, and value choices.",
      "",
      "Only `test/option.test.js` may be changed. Do not change the library to make a test pass.",
    ],
    metadata: {
      representativeReason:
        "Repairing a stale suite without letting it rot into a suite that asserts nothing is routine maintenance, and it is only decidable with an external check.",
      validatorEstablishes:
        "The suite passes against the unmodified library and still fails against four appended Option mutants covering flag recognition, attribute naming and option kind.",
      limitations:
        "Mutation coverage is limited to four Option mutants. The suite deliberately avoids areas covered by other tasks in this repository.",
    },
  },
  {
    id: "cli-subpath-exports",
    repositoryId: "cli-command-core",
    class: "config_change",
    title: "Declare the package entry point and keep lib private",
    editableScope: ["package.json"],
    validator: "validators/cli-exports.mjs",
    knownGood: "known-good/cli-exports.json",
    validatorTimeoutMs: 120_000,
    features: {
      acceptanceCriteriaType: "static_analysis",
      editableFileCount: 1,
      expectedChangeBreadth: "single_file",
      specificationClarity: "explicit",
      verificationCostClass: "moderate",
      reversibility: "reversible_with_review",
    },
    prompt: [
      "This package has no `exports` map, so every file under `lib/` is reachable by consumers. Add",
      "packaging configuration to `package.json` so that:",
      "- the package root resolves to `./index.js`;",
      "- `<pkg>/package.json` remains resolvable;",
      "- no path under `lib/` is reachable directly, and neither is `<pkg>/index.js`;",
      "- a `files` array is declared that includes `index.js` and `lib/`.",
      "",
      "This is an ES module package. Do not change the package name, license, type or main field.",
    ],
    metadata: {
      representativeReason:
        "Declaring a single public entry point while hiding the implementation directory is routine packaging work with an invisible failure mode.",
      validatorEstablishes:
        "The candidate is staged under node_modules and Node's own resolver decides which subpaths load, including that JSON stays reachable in an ES module package.",
      limitations: "Does not cover conditional exports, types entries, or dual CJS/ESM packaging.",
    },
  },
];
